// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vecMultinom
int vecMultinom(NumericVector probs);
RcppExport SEXP simstudy_vecMultinom(SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(vecMultinom(probs));
    return rcpp_result_gen;
END_RCPP
}
// matMultinom
Rcpp::IntegerVector matMultinom(Rcpp::NumericMatrix probmatrix);
RcppExport SEXP simstudy_matMultinom(SEXP probmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probmatrix(probmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(matMultinom(probmatrix));
    return rcpp_result_gen;
END_RCPP
}
