// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matMultinom
Rcpp::IntegerVector matMultinom(Rcpp::NumericMatrix probmatrix);
RcppExport SEXP simstudy_matMultinom(SEXP probmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probmatrix(probmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(matMultinom(probmatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"simstudy_matMultinom", (DL_FUNC) &simstudy_matMultinom, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_simstudy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
