# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multinomial
#'
vecMultinom <- function(probs) {
    .Call('simstudy_vecMultinom', PACKAGE = 'simstudy', probs)
}

#' Matrix Multinomial
#'
#' @export
matMultinom <- function(probmatrix) {
    .Call('simstudy_matMultinom', PACKAGE = 'simstudy', probmatrix)
}

