# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecMultinom <- function(probs) {
    .Call(simstudy_vecMultinom, probs)
}

matMultinom <- function(probmatrix) {
    .Call(simstudy_matMultinom, probmatrix)
}

