name: pkgcheck

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on: workflow_dispatch

jobs: 
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'
    steps:
      - uses: assignUser/pkgcheck-action@actual-docker
        
