name: release checks
# only works when this file is in the default branch
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false  
      email:
        description: email 
        required: true
        default: "keith.goldfeld@nyulangone.org"
      token:
        description: email validation token    
        required: true
      platforms:
        description: platforms to check on
        required: true
        default: "c('windows-x86_64-devel','fedora-clang-devel','linux-x86_64-rocker-gcc-san','debian-gcc-devel-nold')"
jobs:
  rhub:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rhub
      - name: Run rhub checks
        run: |
          rhub::validate_email(email = ${{ github.event.inputs.email }}, token = ${{ github.event.inputs.token }})
          rhub::check(platform = ${{ github.event.inputs.platforms }}, email = ${{ github.event.inputs.email }})
        shell: Rscript {0}

