on:
  workflow_dispatch:

name: progress-test

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.create({owner:"assignUser",repo:"simstudy",title:"some issue"})
